name: Run brownfield land collection

on:
  push:
    paths:
      - 'dataset/**'
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

env:
  GITHUB_ACTOR_EMAIL: ${{ secrets.GITHUB_ACTOR_EMAIL }}
  GITHUB_ACTOR_TOKEN: ${{ secrets.GITHUB_ACTOR_TOKEN }}
  GITHUB_ACTOR_USERNAME: ${{ secrets.GITHUB_ACTOR_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Install Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup git
      run: |
        git config user.email "${GITHUB_ACTOR_EMAIL}"
        git config user.name "${GITHUB_ACTOR_USERNAME}"
        git remote set-url origin https://${GITHUB_ACTOR_USERNAME}:${GITHUB_ACTOR_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git checkout master
    - name: Install dependencies
      run: make init
    - name: Collect resources
      run: make collect
    - name: Commit resources
      run: |
        git add collection
        git diff --quiet && git diff --staged --quiet || (git commit -m "Commit files collected on $(date +%F)"; git push origin master)
    - name: Validate collected resources
      run: make validate
    - name: Commit validation files
      run: |
        git add validation
        git diff --quiet && git diff --staged --quiet || (git commit -m "Commit files validated on $(date +%F)"; git push origin master)
    - name: Create dataset and indexes
      run: make harmonise dataset index
    - name: Commit dataset and indexes
      run: |
        git add var index
        git diff --quiet && git diff --staged --quiet || (git commit -m "Commit new dataset and indexes for $(date +%F)"; git push origin master)
